# Generated by Django 5.1.1 on 2024-10-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='category/images')),
            ],
        ),
        migrations.CreateModel(
            name='Catcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app10.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describein1', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=1)),
                ('image', models.FileField(upload_to='category/images')),
                ('instruction1', models.CharField(default='', max_length=200)),
                ('instruction2', models.CharField(default='', max_length=200)),
                ('instruction3', models.CharField(default='', max_length=200)),
                ('instruction4', models.CharField(default='', max_length=200)),
                ('instruction5', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('catcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app10.catcategory')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app10.category')),
            ],
        ),
    ]
