# Generated by Django 5.1.1 on 2024-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(default=1, upload_to='category/images'),
            preserve_default=False,
        ),
    ]
